### ISSUE TITLE
Task list to display all campaigns - front

### ISSUE THREAD

**Issue by FlorczakDavid** [FlorczakDavid/WestMarches#4]
about feature #2 
- [x] clean the default Next.js files
- [x] add a page to be call by the RootLayout
- [x] display a list dynamically from a map
- [x] fetch campaigns list from the server
- [x] display the fetched campaigns' basic data in the list
